env:
  browser: true
  es6: true
  node: true
root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
plugins:
  - "@typescript-eslint"
  - no-relative-import-paths
  - import
  - unused-imports
  - simple-import-sort
rules:
  no-relative-import-paths/no-relative-import-paths:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  simple-import-sort/imports:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/no-default-export:
    - error
  "@typescript-eslint/no-unused-vars":
    - "off"
  "@typescript-eslint/member-delimiter-style":
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces:
    - error
  comma-dangle:
    - error
    - always-multiline
  import/default:
    - "off"
  unused-imports/no-unused-imports:
    - error
  "@typescript-eslint/explicit-function-return-type":
    - error
  "@typescript-eslint/no-explicit-any":
    - "off"
